### ISSUE TITLE
[FEATURE] Add more customizability features

### ISSUE THREAD

**Issue by LegItMate** [Lazap-Development/Lazap#128]
**Is your feature request related to a problem? Please describe.**
I am quite frustrated with being unable to make my whole launcher not look like RGB. And the default background is quite boring and makes me feel old after using the launcher for so long. I require something new and customized! 

**Describe the solution you'd like**
I would like to have an addition of more customizable options, like being able to change the colors of the app's background, titlebar, menu tabs, etc. and be able to have some designs as well; for example gradients in different directions, wavy shapes, mesh gradients, etc. 

**Describe alternatives you've considered**
An alternative could be having some set presets for the launcher themes. On the other hand, it could also be a whole feature including full customizability as requested above. 

**Additional information**
None

**Comment by Uday-007** [comment]
A DEVELOPER FRUSTRATED BY HIS OWN CREATION?!?!??? LMAO

**Comment by Uday-007** [comment]
SOUNDS LIKE A SKILL ISSUE.

**Comment by p0ryae** [comment]
This feat request has been added as a part of the [c75c552](https://github.com/Lazap-Development/Lazap/commit/c75c552d21ce9e0b1178d56f764a277ce4a44a4b) commit. This feature will be a part of the `v0.7` release as well
