### ISSUE TITLE
[BUILD] How to Build Lazap

### ISSUE THREAD

**Issue by snoopyxz** [Lazap-Development/Lazap#138]
hello sorry for the stupid question but how can i build the program to be able to have a .deb and .msi.

**Comment by snoopyxz** [comment]
I already found out sorry, for those who have the same doubt just run the command **yarn tauri:build**

**Comment by p0ryae** [comment]
You can build lazap via `yarn tauri:build`. Keep in mind the installer bundle (`.msi`, `.deb` etc) is dependent on the operating system you're running. For instance, if you're on windows, you are limited to build .msi and .exe bundles only.

**Comment by snoopyxz** [comment]
thanks for your answer, i already tried to do this command but it gives me an error i am building it through linux.

Error:

` DONE  Build complete. The src-tauri/target/webpack_dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
       
   Compiling lazap v0.6.5 (/home/diogo/Transferências/Lazap-main/src-tauri)
    Finished release [optimized] target(s) in 1m 26s
thread '<unnamed>' panicked at 'Can't detect any appindicator library', src/build.rs:390:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Done in 102.30s.
`

**Comment by p0ryae** [comment]
You're missing libappindicator devel library. 

Ensure you install all system dependencies in here:
https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux

If the issue persists, install `libappindicator-gtk3-devel` (pkg name might vary depending on the distro)

**Comment by snoopyxz** [comment]
thanks again for the answer now it's working thank you very much for the help.

**Comment by snoopyxz** [comment]
hello sorry to be opening again I am having an error when I run the command `yarn tauri:serve` in the new version 0.7

Error.: 

```
        Info Watching /home/diogo/Documentos/Lazap-main/src-tauri for changes...
   Compiling lazap v0.7.0 (/home/diogo/Documentos/Lazap-main/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 34.83s
thread 'main' panicked at 'JSON was not well-formatted: Error("missing field `enable_spotify`", line: 1, column: 187)', src/modules/storage.rs:93:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by LegItMate** [comment]
It seems that the code expects `enable_spotify` and `enable_overlay` fields in the LauncherData.json config file as defined here https://github.com/Lazap-Development/Lazap/blob/main/src-tauri/src/modules/storage.rs#L83-L93.

The best solution is to delete your LauncherData.json file if you don't have any data saved or don't care about losing the data OR you could just add those 2 fields manually in the file and set the values to `false`, however you may face other incompatibility issues by doing this(which can also help us find more issues)

This seems to be a backward compatibility issue which has now come to our attention thanks to you 👍🤦‍♂️

**Comment by snoopyxz** [comment]
Np thanks.
