### ISSUE TITLE
[BUG] Games are not listing after relaunch and slow to list 

### ISSUE THREAD

**Issue by psychrabi** [Lazap-Development/Lazap#145]
I re ran the launcher after closing it and found that the games list empty and it took few minutes for it to load.
I checked the %appdata% folder and there is data from previous launch but game listing is slow 
![image](https://github.com/Lazap-Development/Lazap/assets/17595403/85c8b867-2049-48c7-ad8d-131d8d73c736)

**Comment by p0ryae** [comment]
Hi @psychrabi thanks for the report. Did you delete your `com.lazap.config` prior to launching lazap v0.8?

**Comment by psychrabi** [comment]
Yes, I did.

**Comment by p0ryae** [comment]
You shouldn't experience any delays, especially in the latest release. 

This issue is likely related to the other issue you opened (#144). 

Going to close this for the sake of organization in terms of communcation.
