### ISSUE TITLE
Use `serde(transparent)`

### ISSUE THREAD

**Issue by Lucretiel** [Lazap-Development/Lazap#149]
https://github.com/Lazap-Development/Lazap/blob/151995e8a2a993b0287bf65b3dd3303a480cab4e/src-tauri/src/launchers/steam.rs#L20

use `derive(deserialize)` and `serde(transparent)` here, to avoid the need for a custom deserializer

**Comment by p0ryae** [comment]
Wow, I didn't know such even existed. That's going to cut down a huge chunk of deserialize code. I remember trying to find out about such, but then resorted to implementing a whole deserializer.

Anyways, fixed in 0a2ff9c. Thanks once again!
