### ISSUE TITLE
`static mut` is ALWAYS a mistake

### ISSUE THREAD

**Issue by Lucretiel** [Lazap-Development/Lazap#151]
https://github.com/Lazap-Development/Lazap/blob/151995e8a2a993b0287bf65b3dd3303a480cab4e/src-tauri/src/addons/spotify.rs#L17-L26

There are several preferable options here:

- Use `std::sync::OnceLock`, a safe way to ensure a global variable is initialized at most once, and then is read-only forever afterwards.
- use `actix_web::web::Data`, the standard way to pass data dynamically into a request handler
- Make your request handler a local lambda, and capture the data you're interested in by reference or by move.
- In the worst case, use an `Arc<Mutex<T>>` to pass the data around. This should be your last resort.

**Comment by p0ryae** [comment]
Hi @Lucretiel thank you for bringing this up to my attention. 

I was curious to know if using a mix of different types of global variables (for example `actix_web::web::Data` and tauri state) would be a bad practice as well. I'm currently in the process of transforming spotify client id and secret into actix_web state data and the other global variables into tauri state data for obvious reasons.

**Comment by p0ryae** [comment]
Hey @Lucretiel just doing a follow-up :) please read the comment I posted above. I would highly appreciate your input on this matter.

**Comment by p0ryae** [comment]
Fixed in the 56e020a commit. Although the issue opener did not respond, I decided to fall back and use `OnceLock` and `Arc<Mutex<T>>>`. The `actix_web::web::Data` solution wouldn't have been helpful for the tauri calls.
