### ISSUE TITLE
[BUG] Lazap doesn't launch on Pop OS (Ubuntu) when installed from deb file

### ISSUE THREAD

**Issue by ASOwnerYT** [Lazap-Development/lazap#59]
**Describe the bug**
When I launch Lazap, it doesn't launch. When I launch it from the command line, I get this error:
`lazap: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**To Reproduce**
1. On the latest version of Pop OS, install the deb file
2. Type `lazap` in the terminal
3. Get error

**Expected behavior**
It should launch

**Screenshots**
![image](https://user-images.githubusercontent.com/23545044/182325096-5d7f4857-ea10-4f20-92de-35b459a63ae2.png)

**Desktop:**
 - OS: Pop OS Linux (an Ubuntu based distro)
 - Browser: Firefox (in case that's somehow relevant?)
 - Version: Release v0.4.0 of Lazap

**Additional information**
None

**Comment by DashCruft** [comment]
Thanks for filing an issue!

I believe you are missing libssl-dev. Since you are on PopOS, try installing it by using apt-get.

Let me know about the result!

**Comment by DashCruft** [comment]
It appears to me that some Linux Distros have this issue when using .deb

Good news is that there's a workaround to it. I'll update the packages as soon as possible and notify.

Thanks for bringing this into my attention.

**Comment by DashCruft** [comment]
Issue fixed in e665c24.

**Comment by ASOwnerYT** [comment]
After updating to the latest version of Lazap by downloading the latest deb file release, I'm having the exact same issue again with the exact same error. I don't think anything on my system has changed that could have affected this.

**Comment by DashCruft** [comment]
Thanks for reporting this issue again. I probably forgot to compile openssl (somehow)

Let me check. I'll keep you updated.

**Comment by DashCruft** [comment]
This issue should be fixed in the `0.5.1` release:
https://github.com/Lazap-Development/lazap/releases/tag/v0.5.1

Hopefully I won't forget to add vendored openssl for linux builds in future lol
