### ISSUE TITLE
[FEATURE]  allow the window to be moved from more of the top bar

### ISSUE THREAD

**Issue by JacktheDevel0per** [Lazap-Development/lazap#62]
**Is your feature request related to a problem? Please describe.**
it is hard to find the line to grab onto the window

**Describe the solution you'd like**
allow the window to be moved from more of the top bar, I am not sure how possible this is though.

**Describe alternatives you've considered**
making some sort of top bar indicator?

**Additional information**
Latest Build I found on github, with Tauri ofc

**Comment by DashCruft** [comment]
A few modifications in the CSS should get the job done.

This is known to be a problem in Tauri https://github.com/tauri-apps/tauri/issues/3277 only during specific scenarios

I'll work on a fix.

**Comment by DashCruft** [comment]
@JacktheDevel0per Thanks again for reporting this issue.

This issue shouldn't exist anymore in commit b4f0635.

I'll be updating the builds for release 0.4 as well. Feel free to reopen in case you still have a problem.
