### ISSUE TITLE
[FEATURE] Flatpak Support

### ISSUE THREAD

**Issue by ASOwnerYT** [Lazap-Development/Lazap#66]
**Is your feature request related to a problem? Please describe.**
With the current way its distributed, there are problems such as dependency errors, no auto update, etc. 

**Describe the solution you'd like**
Distribute Lazap as a Flatpak on Flathub. I think Lazap will work very well as a Flatpak.

**Describe alternatives you've considered**
Continue to distribute Lazap for Linux the way it is and have issues

**Additional information**
It might be difficult to set up properly but I think it will be worth it for the future of Lazap on Linux

**Comment by DashCruft** [comment]
Auto-Update will come soon to lazap (probably in the next release).

We will consider adding flatpak sometimes near the future.

Keeping this issue open until implemented.

**Comment by DashCruft** [comment]
Just as an update.

It's highly unlikely Flatpak support will get added for lazap until Tauri themselves come up with the right approach.

More Information here: https://github.com/tauri-apps/tauri/issues/3619

We will still keep this issue open and keep it updated.

**Comment by p0ryae** [comment]
There seems to be a workaround to creating Flatpaks
. 
https://github.com/tauri-apps/wry/issues/811#issuecomment-1352065240

Although we are going to stick with our current provided bundles for now. It's already hard to create an auto-updater on linux with .tar.zst and .deb packages let alone the new flatpack updating mechanism. (Auto-Update is going to be a feature in the next release, `0.7`)
