### ISSUE TITLE
[BUG] Duplicate games when Lutris is syncing with Steam

### ISSUE THREAD

**Issue by ASOwnerYT** [Lazap-Development/Lazap#74]
**Describe the bug**
 Lutris syncs with the Steam library, and Lazap gets games from both Lutris and Steam, so there are duplicate steam games in Lazap.

**To Reproduce**
1. Sync Steam games in Lutris
2. Open Lazap
3. See duplicate games issue

**Expected behavior**
There shouldn't be duplicate games. Maybe link/group the games together and choose one launcher other the other, or even better have a feature where it shows what launchers are for a game.

**Desktop:**
 - OS: Linux (Pop OS)
 Affected operating systems are Linux only

**Comment by DashCruft** [comment]
We’re going to fix this issue on the next release.

Thanks for reporting!

**Comment by LogicApples** [comment]
This issue is now being fixed in #118. 
If it's approved you can expect it to be added to the main branch in the next release
