### ISSUE TITLE
[BUG] Lazap opens, than immediately closes

### ISSUE THREAD

**Issue by pnes** [Lazap-Development/lazap#84]
Once i click the Lazap application it seems to minimize than just completely disappear, even after uninstalling an reinstalling,

OS: Windows 10

**Comment by LogicApples** [comment]
Hello,

First of all this is a completely new issue that we have not got before so we'd need some information.

did you download lazap directly from github releases or did you build it yourself - if so which branch,

how much time does it take between minimizing and closing itself.

Greetings,

**Comment by ScopeOpen** [comment]
> Once i click the Lazap application it seems to minimize than just completely disappear, even after uninstalling an reinstalling,
> 
> OS: Windows 10

It seems as if you said it’s fixed (on discord), if so please let us know so we can close this. Don’t want any issues left open it they’re not needed.
