### ISSUE TITLE
[BUG] Custom Games do not run

### ISSUE THREAD

**Issue by Mert-Coding** [Lazap-Development/lazap#90]
**Describe the bug**
I can add my game from my external hdd as a custom game but can't run it from lazap.

The location of my game.
=> **`"D:\SW BattleGround 2\STAR WARS Battlefront II\starwarsbattlefrontii.exe"`**

**To Reproduce**
1. Add a Custom Game located in a different hdd.
2. Launch it.

**Expected behavior**
Run my game from my hdd.

**Screenshots**

![image](https://user-images.githubusercontent.com/65625734/190896546-639fcf5e-6835-4be8-b025-52b9b88490a0.png)

![image](https://user-images.githubusercontent.com/65625734/190896600-34f16112-fc30-4105-9472-beaec30637ef.png)
*  The text in the bottom is turkish and the translation is => This location can't be found by Windows. Be sure that you wrote the name right and try again
* The buttons label is "OK".

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 11

**Comment by LegItMate** [comment]
This issue has been identified, seems like custom games was not tested enough before release. The fix is being worked on and will be available in the next patch release. 

Thank you for checking out Lazap and pointing out this issue!

**Comment by DashCruft** [comment]
This issue is addressed and fixed in [0cacc67](https://github.com/Lazap-Development/lazap/commit/0cacc6734e43a41719df81987a53e6f4fc96870f) and is included in the new release of v0.6.1.

Closing this. Thank you for the report and if you still reencounter the issue, let us know here.
